# Generated by Django 4.2.2 on 2023-06-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_company', models.IntegerField(db_column='id_company', verbose_name='Id da Empresa')),
                ('name_brand', models.CharField(db_column='name_brand', max_length=100, verbose_name='Nome da Marca')),
                ('enabled', models.CharField(db_column='enabled', max_length=3, verbose_name='Ativo')),
            ],
            options={
                'db_table': 'brand',
            },
        ),
    ]
